name: Fetch Food4Thought redirect.html
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout master from this repo
      - uses: nolim1t/actions/torscp@master
        name: Deploy site to hidden service over SCP
        env:
          SRC: ${{ secrets.SRC }}
          DEST: ./food4thought.html
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Run LS on default directory
        run: ls 
      - name: Commit food4thought.html to this repo
        uses: stefanzweifel/git-auto-commit-action@v2.2.0
        with:
          commit_message: Update food4thought with latest redirect.html
          branch: ${{ github.head_ref }}
          file_pattern: food4thought.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
