name: Fetch Food4Thought redirect.html
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout master from this repo
      - uses: nolim1t/actions/torscp@master
        name: Copy redirect file from food4thought onion
        env:
          SRC: ${{ secrets.SRC }}
          DEST: ./food4thought.html
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Run LS on default directory
        run: ls 
      - name: Add food4thought to git staged directory
        run: git add food4thought.html
      - name: Set up git config
        run: git config --global user.email "autobot@noreply.github.com"
      - name:  Set up git username
        run: git config --global user.name "Github commit bot"
      - name: Commit food4thought.html to this repo
        run: git commit -m "Commit food4thought.html to repo"
      - name: Push to upstream
        run: git push -u origin HEAD
