name: Fetch Food4Thought redirect.html every 12 hours
on:
  schedule:
    - cron: '* 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout master from this repo
      - name: Checkout master at HEAD
        run: git checkout master
      - uses: nolim1t/actions/torscp@0.1.1
        name: Copy redirect file from food4thought onion
        env:
          SRC: ${{ secrets.SRC }}
          DEST: ./food4thought.html
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Run LS on default directory
        run: ls 
      - name: Add food4thought to git staged directory
        run: git add food4thought.html
      - name: Set up git config
        run: git config --global user.email "nolim1t@users.noreply.github.com"
      - name:  Set up git username
        run: git config --global user.name "nolim1t-action"
      - name: set up SSH target
        run: git remote add originssh git@github.com:nolim1t/lncm-pos-redirect.git
      - name: Commit food4thought.html to this repo
        run: git commit --allow-empty -m "Updating latest food4thought.html from retail box to repo for linking purposes"
      - name: Update host key for github
        run: mkdir -p ~/.ssh && echo "${PRIVATE_KEY}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Push to upstream
        run: git push originssh master
